

trigger:
  branches:
    include:
      - main  # change if needed

pool:
  name: 'Default'

variables:
  buildConfiguration: 'Release'
  outputDir: '$(Build.ArtifactStagingDirectory)/publish'

steps:
# Install .NET SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'  # Use your .NET version
    installationPath: $(Agent.ToolsDirectory)/dotnet

- checkout: self

- script: |
    cd src/dotnet
    dotnet restore
    displayName: 'Restore NuGet Packages'

# # Restore dependencies
# - script: dotnet restore
#   displayName: 'Restore NuGet Packages'

# Build solution
- script: dotnet build --configuration $(buildConfiguration) --no-restore
  displayName: 'Build Solution'

# Run unit tests
- script: dotnet test --no-build --configuration $(buildConfiguration) --logger:trx
  displayName: 'Run Unit Tests'

# Publish the app
- script: dotnet publish --configuration $(buildConfiguration) --output $(outputDir)
  displayName: 'Publish Application'

# Publish artifacts for later use or deployment
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(outputDir)'
    artifactName: 'drop'
    publishLocation: 'Container'