trigger:
- main


stages:
- stage: Deploy
  jobs:
  - job: DeployJob
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      # Variables can be referenced using Key Vault secret names
      - group: MyKeyVaultSecrets  # Azure DevOps Variable Group linked to Key Vault secrets
    steps:
    - task: AzureKeyVault@2
      name: FetchSecrets
      inputs:
        azureSubscription: 'abb-test-demo'
        KeyVaultName: 'abbtest-kv'
        SecretsFilter: '*'
        RunAsPreJob: true

    - script: |
        echo "Starting deployment..."
        echo "Using secret: $(mySecretName)" 
        echo "Secret 'mySecretName' is successfully fetched and will be used for deployment."
      displayName: 'Show secret usage (without exposing secret)'

    - script: |
        # Example: use the secret in deployment commands
        # For example, pass secret as environment variable
        export MY_SECRET=$(mySecretName)
        echo "Deploying application with secret."
        # Your deployment commands here, e.g. helm upgrade or kubectl apply
      displayName: 'Deploy with secret from Key Vault'
