# Use the official Nginx base image
FROM nginx:latest

COPY ./html /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/nginx.conf
RUN apt-get update && apt-get install -y gettext-base

# Expose port 80
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]
